[platformio]
default_envs = portenta_h7_m7

[env:portenta_h7_m7]
platform = platformio/ststm32@20.0.0
board = portenta_h7_m7
framework = arduino
build_src_filter =
    -<*>
    +<main.cpp>
    +<motors.cpp>
    +<pixhawk.cpp>
lib_deps =
    okalachev/MAVLink@2.0.29
upload_protocol = dfu
monitor_speed = 57600
